apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-spring-boot-app-k8s-999
spec:
  strategy:
    $retainKeys:
      - type
      - rollingUpdate
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 33%
  selector:
    matchLabels:
      app: sample-spring-boot-app-k8s-999
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
      labels:
        app: sample-spring-boot-app-k8s-999
    spec:
      containers:
        - name: sample-spring-boot-app-k8s-999
          image: cnoe-demo/sample-spring-boot-app-k8s-999
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/readiness
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          resources:
            limits:
              memory: 1024Mi
---
apiVersion: v1
kind: Service
metadata:
  name: sample-spring-boot-app-k8s-999
spec:
  type: NodePort
  selector:
    app: sample-spring-boot-app-k8s-999
  ports:
    - port: 8080
      nodePort: 30000
