name: JIB container publish

on: [push, workflow_dispatch]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check token presence (debug, non stampa il valore!)
        run: |
          if [ -z "${{ secrets.THE_TOKEN }}" ]; then
            echo "❌ No token found"
            exit 1
          else
            echo "✅ Token is present"
          fi    
      - name: JIB container build and publish
        uses: MathieuSoysal/jib-container-publish.yml@v2.1.5
        with:
          PASSWORD: ${{ secrets.THE_TOKEN }}
          java-version: 21
